### ISSUE TITLE
Can't connect after installation

### ISSUE THREAD

**Issue by Prisoner709** [JeffLabonte/NordVPN_App_Fedora#2]
Hi, i have installed nordvpn with your script on Fedora 30. All it's ok during installation, ok login, ok configurations. The daemon is active, but when i try "nordvpn connect" command like user, this is the result: "Whoops! We can't connect you to 'fr354.nordvpn.com'. Please try again. If the problem persists, contact our customer support." Thanks for your interest.

**Comment by JeffLabonte** [comment]
I will test it out once I have a minute to spare! :) 

Although I have noticed that rebooting your PC helps.

**Comment by JeffLabonte** [comment]
I have updated the version of nordvpn to 3.0.0-5, it has fix the issue for me! 

I have begun by purging the old version (`./nordvpn.sh purge`) then install it again (`./nordvpn.sh install`).
Afterwards, I rebooted my laptop and everything started working again! 

Keep me posted!

**Comment by Prisoner709** [comment]
Hi Jeff. Ok solved. I deleted nordvpn, disabled the nordvpnd daemon, restarted the pc. I installed nordvpn again with your script, I restarted the PC again and it works. Thanks for support and for time.

**Comment by JeffLabonte** [comment]
You are very welcome! I have also worked on the script lately! If it can make things easier! 

Time is very scarce these days! XD
