### ISSUE TITLE
Didn't enable service

### ISSUE THREAD

**Issue by leogex01** [JeffLabonte/NordVPN_App_Fedora#4]
I'm using fedora 29 and had to start nordvpnpsd and nordvpnpud- couldn't connect to daemon error.. No big deal, didn't see it in the script and gave it a shot. Other than that it worked perfectly.

**Comment by JeffLabonte** [comment]
The server should be enabled and started right away... Perhaps my comprehension of the flag --now is wrong! I will look into it! Thank you for reporting it!
